services:
  # 1. The Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: apex_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # 2. The Backend API Server
  api-server:
    container_name: apex_api
    build:
      context: ./api-server
    restart: unless-stopped
    ports:
      # Esta linha garante que a porta 3001 de dentro do container
      # seja acessível pela porta 3001 da sua máquina (localhost).
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: